services:
  - type: web
    name: seo-tool
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium   # ⬅️ sans --with-deps
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
