services:
  - type: web
    name: seo-tool
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: bash -c "python -m playwright install chromium && uvicorn app:app --host 0.0.0.0 --port $PORT"
